apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: frontend
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetcpuutil }}