webVersion: v1
kind: Service 
metadata:
  namespace: expense
  name: frontend
  
spec:
  type: LoadBalancer
  selector:
   app: frontend
   tier: web
   project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 # this is service port
    targetport: 8080 # this is container port.